USE Test_1

-- Tạo bảng
CREATE TABLE KhachHang(
  MaKH varchar(30) NOT NULL,
			
  HoTenKH nvarchar(30)  NOT NULL,
  DiaChi nvarchar(30) NULL,
  SoDienThoai  varchar(50) NULL,
  GioiTinh nvarchar(30) 
					CHECK(GioiTinh IN( N'Nam', N'Nữ')) NULL,
  CONSTRAINT PK_KhachHang_MaKH PRIMARY KEY(MaKH)
)

CREATE TABLE LoaiSP(
MaLoaiSP VARCHAR(30) NOT NULL,
TenLoaiSP NVARCHAR(50) NOT NULL,
CONSTRAINT PK_LoaiSP_MaLoaiSP PRIMARY KEY (MaLoaiSP)
)

CREATE TABLE NhaCungCap(
MaNCC INT IDENTITY,
TenNhaCC NVARCHAR(100) NOT NULL,
DiaChi NVARCHAR(30) NULL
)

CREATE TABLE SanPham(
MaSP VARCHAR(30) NOT NULL,
TenSP NVARCHAR(30) NOT NULL,
DonViTinh NVARCHAR(30) NOT NULL,
SoLuong INT NULL,
DonGia DECIMAL(18,0) NULL,
NgaySanXuat DATE NULL,
MaLoaiSP VARCHAR(30) NOT NULL,                      
MaNhaCC INT NULL,
TinhTrang NVARCHAR(30) NULL
CONSTRAINT PK_SanPham_MaSP PRIMARY KEY (MaSP),
CONSTRAINT FK_LoaiSP_TenLoaiSP FOREIGN KEY (MaLoaiSP)
REFERENCES dbo.LoaiSP
)

CREATE TABLE NhanVien(
MaNV CHAR(10) 
		DEFAULT  'NV[0-9][0-9]' NOT NULL,
HoTen NVARCHAR(50) NOT NULL,
GioiTinh NVARCHAR(50) 
			CHECK(GioiTinh IN( N'Nam', N'Nữ')) NULL,
DienThoai NVARCHAR(50) NULL,
NgayVaoLam DATE NULL,
TrangThai NVARCHAR(50) NULL,
CONSTRAINT PK_NhanVien_MaNV PRIMARY KEY (MaNV)
)

CREATE TABLE DonHang(
MaDonHang VARCHAR(30) NOT NULL,
MaKH VARCHAR(30) NULL,
MaNV CHAR(10) NULL,
NgayLap DATE NULL,
TongTien DECIMAL(18,0) 
		DEFAULT 0 NULL,
TrangThaiDH NVARCHAR(30) NULL
CONSTRAINT PK_DonHang_MaDonHang PRIMARY KEY (MaDonHang),
CONSTRAINT FK_NhanVien_MaNV FOREIGN KEY (MaNV) REFERENCES dbo.NhanVien,
CONSTRAINT FK_KhachHang_MaKH FOREIGN KEY (MaKH) REFERENCES dbo.KhachHang
)

CREATE TABLE ChiTietDonHang(
SoLuong INT NOT NULL,
DonGia DECIMAL(18,2) NULL,
CONSTRAINT FK_ChiTietDonHang_MaSP FOREIGN KEY (MaSP)
REFERENCES dbo.SanPham,
CONSTRAINT FK_ChiTietDonHang_MaDonHang FOREIGN KEY (MaDonHang) 
REFERENCES dbo.DonHang,
CONSTRAINT PK_ChiTietDonHang_MaSP_MaDonHang PRIMARY KEY (FK_ChiTietDonHang_MaSP,FK_ChiTietDonHang_MaDonHang)
)







